### ISSUE TITLE
UnboundLocalError: local variable 'mutation' referenced before assignment

### ISSUE THREAD

**Issue by ichxw** [JakeColtman/bartpy#44]
Hi Jake, 
When running example code as beflow:
`import numpy as np
import pandas as pd

from matplotlib import pyplot as plt

from bartpy.sklearnmodel import SklearnModel

x = np.random.normal(0, 0.5, size=1000)
X = pd.DataFrame({"x": x})
y = 2 * x + 4 * np.power(x, 3)
plt.scatter(x, y)

model = SklearnModel(n_jobs=1)

model.fit(X, y)
plt.scatter(x, model.predict())
plt.scatter(x, y)`

I got the following error:
0%|          | 0/200 [00:00<?, ?it/s]Starting burn
Traceback (most recent call last):

  File "<ipython-input-30-63dd6f0ffc1e>", line 15, in <module>
    model.fit(X, y)

  File ".../BART/bartpy-master/bartpy-master/bartpy/sklearnmodel.py", line 134, in fit
    self.extract = Parallel(n_jobs=self.n_jobs)(self.f_delayed_chains(X, y))

  File ".../anaconda3/lib/python3.6/site-packages/joblib/parallel.py", line 921, in __call__
    if self.dispatch_one_batch(iterator):

  File ".../anaconda3/lib/python3.6/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)

  File ".../anaconda3/lib/python3.6/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)

  File ".../anaconda3/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)

  File ".../anaconda3/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()

  File ".../anaconda3/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]

  File ".../anaconda3/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]

  File ".../BART/bartpy-master/bartpy-master/bartpy/sklearnmodel.py", line 31, in run_chain
    model.store_acceptance_trace)

  File ".../BART/bartpy-master/bartpy-master/bartpy/samplers/modelsampler.py", line 43, in samples
    self.step(model, trace_logger)

  File ".../BART/bartpy-master/bartpy-master/bartpy/samplers/modelsampler.py", line 26, in step
    result = step()

  File ".../BART/bartpy-master/bartpy-master/bartpy/samplers/schedule.py", line 48, in <lambda>
    yield "Tree", lambda: self.tree_sampler.step(model, tree)

  File ".../BART/bartpy-master/bartpy-master/bartpy/samplers/unconstrainedtree/treemutation.py", line 47, in step
    mutation = self.sample(model, tree)

  File ".../BART/bartpy-master/bartpy-master/bartpy/samplers/unconstrainedtree/treemutation.py", line 40, in sample
    ratio = self.likihood_ratio.log_probability_ratio(model, tree, proposal)

  File ".../BART/bartpy-master/bartpy-master/bartpy/samplers/treemutation.py", line 80, in log_probability_ratio
    return self.log_transition_ratio(tree, mutation) + self.log_likihood_ratio(model, tree, mutation) + self.log_tree_ratio(model, tree, mutation)

  File ".../BART/bartpy-master/bartpy-master/bartpy/samplers/unconstrainedtree/likihoodratio.py", line 69, in log_likihood_ratio
    #mutation: GrowMutation = mutation

UnboundLocalError: local variable 'mutation' referenced before assignment

Do you know where the problem is? Thank you.
xiangwei

**Comment by lonelykid** [comment]
Same here.

**Comment by lonelykid** [comment]
The ReadOneTrees branch seems working.

**Comment by JakeColtman** [comment]
Hi, Thanks for trying it out and raising an issue :)  I'd pretty strongly recommend working off the `ReadOneTrees` branch rather than master.  I'm going to do some final checks and then merge the changes back in.

**Comment by DaveDarrel** [comment]
Same problem here :(

Could you add an example of how to use ReadOneTrees branch ? 

Thanks!

**Comment by WilsonAntony-171060** [comment]
como se una la rama ReadOneTrees alguien me ayuda porfavor, tengo el mismo problema de: "local variable 'mutation' referenced before assignment"

**Comment by WilsonAntony-171060** [comment]
**_### ESTO ME SALTA AL EJECUTARLO_**
0%|          | 0/200 [00:00<?, ?it/s]Traceback (most recent call last):

  File "<ipython-input-6-0a1536d97bc4>", line 1, in <module>
    runfile('/home/antony/Python/Datos Panel Solar Validado/Bart_3.py', wdir='/home/antony/Python/Datos Panel Solar Validado')

  File "/home/antony/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/home/antony/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/antony/Python/Datos Panel Solar Validado/Bart_3.py", line 23, in <module>
    model.fit(X, y)

  File "/home/antony/anaconda3/lib/python3.7/site-packages/bartpy/sklearnmodel.py", line 134, in fit
    self.extract = Parallel(n_jobs=self.n_jobs)(self.f_delayed_chains(X, y))

  File "/home/antony/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()

  File "/home/antony/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))

  File "/home/antony/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)

  File "/home/antony/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()

  File "/home/antony/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception

**Comment by b5ck1n** [comment]
Hi, I got the same problem, have you solved it?

**Comment by WilsonAntony-171060** [comment]
Si amigo lo resolvi. La solucion esta en que deberas instalar la libreria
desde la rama que te indica el autor de la libreria
